### ISSUE TITLE
Support `yaml` files

### ISSUE THREAD

**Issue by T0RAT0RA** [Oriflame/backstage-plugins#139]
Provide a way to support `yaml` instead of `json`.

Ex: `all.yaml`:
```yaml
---
- entityRef:
    kind: api
    name: api.foo
  scorePercent: 50
  scoreLabel: Yellow
  scoringReviewDate: '2022-01-01T08:00:00Z'
  scoreSuccess: almost-failure
  areaScores:
  - title: Extensibility
    scorePercent: 50
    scoreLabel: Yellow
    scoreSuccess: almost-failure
  - title: Code
    scorePercent: 100
    scoreLabel: Green
    scoreSuccess: success
  - title: Quality
    scorePercent: 25
    scoreLabel: Red
    scoreSuccess: failure
  - title: Documentation
    scorePercent: 100
    scoreLabel: Green
    scoreSuccess: success
  - title: Operations
    scorePercent: 50
    scoreLabel: Yellow
    scoreSuccess: almost-failure
```

## Feature Suggestion

JSON doesn't support comments so having the scores in YAML enable commenting the score file, for better maintenance.

## Possible Implementation

Adding a new boolean config `useYaml` that would use `.yaml` suffix to the urls, and convert the fileback to JSON before processing it.

## Context

I can provide an implementation once I'm done with #99
